### ISSUE TITLE
Q: Is Iron Router able to render components via yield?

### ISSUE THREAD

**Issue by rclai** [peerlibrary/meteor-blaze-components#44]
``` js
Router.route('/', {
  name: 'MyRoute',
  template: 'MyComponent'
});
```

**Comment by mitar** [comment]
Hm, no. :-( This would just render the logic-less template content. Not a component. You could probably do `template: MyComponent.renderComponent()` there.

**Comment by mitar** [comment]
It seems it should work easily. You just have to use a controller with a different `lookupTemplate` method. This overrides it. But you could easily create a controller class which just inherits from `RouteController`.

``` javascript
var originalLookupTemplate = RouteController.prototype.lookupTemplate;
RouteController.prototype.lookupTemplate = function () {
  if (var component = BlazeComponent.getComponent(this.lookupOption('template'))) {
    return component.renderComponent();
  }
  return originalLookupTemplate.apply(this);
};
```

**Comment by mitar** [comment]
Now that I am thinking, probably it could be possible to create a JavaScript class which is both an `RouteController` and a Blaze Component. That would be an interesting combination.

**Comment by rclai** [comment]
Oh wow, thanks for looking that up so fast. I think I will just use that prototype patch for now but were you thinking of doing something in particular with Iron Router or can I just close this?

**Comment by mitar** [comment]
We could probably made that into a package. Or push them upstream with a weak dependency in iron-router.

**Comment by rclai** [comment]
Looks like that prototype hack does not work because it's the wrong one to hack, these are the other prototypes that need to be patched:

https://github.com/iron-meteor/iron-controller/blob/c4642d6b53ecd3584a09cd8c93505bc6e5291d71/lib/controller.js#L57

https://github.com/iron-meteor/iron-layout/blob/daf50f862272e2b84f30950d27049451145cb8b9/layout.js#L96

**Comment by mitar** [comment]
Does it work or does it not work?

**Comment by rclai** [comment]
It does, sorry I messed up.

**Comment by rclai** [comment]
So what did you want to do about this? Did you want to create a package for making BC compatible with IR?

**Comment by mitar** [comment]
Patch into Meteor changing all necessary bits to have officially all extension points needed by Blaze Components was just merged into its `development` branch: https://github.com/meteor/meteor/commit/eff8016b5a7a981fc56beb531ece52de5b3d7101

Based on that I made this pull request to Iron Router: https://github.com/iron-meteor/iron-dynamic-template/pull/11

If it is merged in Blaze Components should work out of the box with iron router.

**Comment by mitar** [comment]
@rclai: Could you test if using that branch of Iron Router works for you? (You do not have to upgrade to latest Meteor, because at the moment Blaze Components monkey-patch it with what was currently merged in.)

**Comment by mitar** [comment]
Try with 0.9.1 version.

**Comment by rclai** [comment]
Are you talking about [this branch](https://github.com/mitar/iron-dynamic-template/tree/patch-template)?

**Comment by mitar** [comment]
Yes.

**Comment by mitar** [comment]
Yes.

**Comment by rclai** [comment]
For some reason I got this error:

```
Conflict: Constraint iron:layout@1.0.7 is not satisfied by iron:layout 1.0.0-pre3.
Constraints on package "iron:layout":
* iron:layout@=1.0.0-pre3 <- top level
* iron:layout@1.0.7 <- iron:router 1.0.7 <- profab:core 0.1.0
* iron:layout@1.0.7 <- iron:controller 1.0.7 <- iron:router 1.0.7
```

**Comment by mitar** [comment]
Why you have a top level constraint on `1.0.0-pre3`?

**Comment by rclai** [comment]
Oh whoops I forgot to `git checkout patch-template`.

**Comment by rclai** [comment]
Okay, my routes error out with this now: 

```
TypeError: undefined is not a function
    at [object Object].Controller (packages/iron:controller/lib/controller.js:23:1)
    at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:14:1)
    at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
    at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
    at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
    at Object.router (packages/iron:router/lib/router.js:15:1)
    at next (/root/.meteor/packages/webapp/.1.2.0.xaqlky++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
    at Object.Package [as handle] (packages/cfs:http-methods/http.methods.server.api.js:425:1)
    at next (/root/.meteor/packages/webapp/.1.2.0.xaqlky++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:190:15)
    at Function.app.handle (/root/.meteor/packages/webapp/.1.2.0.xaqlky++os+web.browser+web.cordova/npm/node_modules/connect/lib/proto.js:198:3)
```

**Comment by mitar** [comment]
You will have to give more information. :-) Like, what exactly does not work.

**Comment by mitar** [comment]
BTW, you do not need the patch above anymore.

**Comment by rclai** [comment]
Huh? So am I supposed to just upgrade to 0.9.2 and that's it?

**Comment by mitar** [comment]
Yes. Just upgrade to 0.9.2 and use the `patch-template` branch of `dynamic-template`.

**Comment by rclai** [comment]
Oh, well it's not working, for some reason it (iron layout branch) breaks iron:controller and I can't visit any route. It shows the error in the client-side.

**Comment by mitar** [comment]
Hm. Can you make a small example where it breaks?

**Comment by rclai** [comment]
I'll try that later, but the error happens [here](https://github.com/iron-meteor/iron-controller/blob/master/lib/controller.js#L23).

**Comment by mitar** [comment]
This is really strange. I think there is maybe some mismatch of versions you have? Do you have everything on your latest version? What does `.meteor/versions` say?

**Comment by rclai** [comment]
```
iron:controller@1.0.7
iron:core@1.0.7
iron:dynamic-template@1.0.7
iron:layout@1.0.7
iron:location@1.0.7
iron:middleware-stack@1.0.7
iron:router@1.0.7
iron:url@1.0.7
```

**Comment by rclai** [comment]
I found a way to render a Blaze Component without having to use the `lookupTemplate` monkey-patch. You would have to use the `action` function unfortunately.

``` js
Router.route('/my-route', {
  'name': 'routeName',
  action: function () {
    // My solution to make sure the component doesn't get re-rendered in case I had 
    // multiple routes using the same template. In most cases you won't need this check.
    if (!BlazeComponent.getComponentForElement($('#MyComponentId').get(0))) {
      this.render(BlazeComponent.getComponent('MyComponentRegisteredName').renderComponent());
    }
  }
});
```

**Comment by MatejJan** [comment]
The easiest solution I found is to simply wrap the component into a normal template.

```
<template name="myComponent">
  {{> MyComponent}}
</template>

<template name="MyComponent">
  …
</template>
```

You would then point the router to render `myComponent` template.

**Comment by mitar** [comment]
I suggest you use [Flow Router](https://github.com/kadirahq/flow-router). That one is the one I am using in my projects. See [example app here](https://github.com/mitar/council-app).

I have some code made which would make Iron Router easier to use (route would be the same as component), but I have not yet fixed all the quirks.

**Comment by mitar** [comment]
See #79.

**Comment by MatejJan** [comment]
> I suggest you use Flow Router. That one is the one I am using in my projects. See example app here.

Will check it out, was not aware of it yet.

(What is Meteor's recommendation for routing these days anyway?)

**Comment by mitar** [comment]
Iron Router or Flow Router, but [guide now mentions only Flow Router](https://github.com/meteor/guide/blob/master/content/routing.md).

**Comment by rclai** [comment]
I did use the template proxy method at some point. But I'm more inclined to using blaze layout to render these components now.
